export const apiGatewayJoinTokenParam = 'joinToken'
export const joinTokenParam = 'joinToken'
export const webSocketParam = 'webSocket'
export const positionParam = 'position'
export const pageParam = 'page'
