name: CI

on: [push, pull_request]

env:
  npm_config_engine_strict: true

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:

    # checkout a dependent project
    - name: Checkout cloud-core
      uses: actions/checkout@v4
      with:
        repository: tstibbs/cloud-core
        path: 'cloud-core' # will resolve to /home/runner/work/pdf-viewer-sync/pdf-viewer-sync/cloud-core

    # checkout 'this' project
    - name: Checkout pdf-viewer-sync
      uses: actions/checkout@v4
      with:
        path: 'pdf-viewer-sync' # will resolve to /home/runner/work/pdf-viewer-sync/pdf-viewer-sync/pdf-viewer-sync

    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Set up environment
      run: mkdir cdk.tmp
      working-directory: pdf-viewer-sync/backend
    - name: Set up test environment
      run: cp dummy.env .env
      working-directory: pdf-viewer-sync/backend

    - name: Load cloud-core utils dependencies
      run: npm ci
      working-directory: cloud-core/aws/utils
    - name: Load cloud-core ui dependencies
      run: npm ci
      working-directory: cloud-core/ui

    # root
    - run: npm ci
      working-directory: pdf-viewer-sync

    # backend
    - run: npm ci
      working-directory: pdf-viewer-sync/backend
    - run: npm run testsynth
      working-directory: pdf-viewer-sync/backend
    - run: npm run test
      working-directory: pdf-viewer-sync/backend

    # frontend
    - run: npm ci
      working-directory: pdf-viewer-sync/ui-additions
    - run: npm run download-deps
      working-directory: pdf-viewer-sync/ui-additions
    - run: npm run build
      working-directory: pdf-viewer-sync/ui-additions
